##
# @File: ServiceList.srv
# @Date: 12 August 2019
# @Author: Justin Whitaker
#
# @Brief
# A list of services that a behavior offers for the user to interact with
#
# @behavior_name
# The behavior that the services belong to
#
# @services
# The array of services that are offered
##

---
string behavior_name
interface_msgs/Service[] services
