# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setBaseSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 191, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_refresh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_refresh.setObjectName("button_refresh")
        self.gridLayout.addWidget(self.button_refresh, 1, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.treeWidget = QtWidgets.QTreeWidget(self.gridLayoutWidget)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.treeWidget, 0, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(840, 530, 141, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_submit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_submit.setObjectName("button_submit")
        self.horizontalLayout.addWidget(self.button_submit)
        self.serviceStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.serviceStack.setGeometry(QtCore.QRect(250, 10, 758, 530))
        self.serviceStack.setObjectName("serviceStack")
        self.pageComplete = QtWidgets.QWidget()
        self.pageComplete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pageComplete.setObjectName("pageComplete")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageComplete)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(740, 200, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.pageComplete)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.text_input_c = QtWidgets.QLineEdit(self.pageComplete)
        self.text_input_c.setObjectName("text_input_c")
        self.verticalLayout.addWidget(self.text_input_c, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(740, 250, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.serviceStack.addWidget(self.pageComplete)
        self.pageSend = QtWidgets.QWidget()
        self.pageSend.setObjectName("pageSend")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageSend)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(740, 200, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.pageSend)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.text_input_s = QtWidgets.QLineEdit(self.pageSend)
        self.text_input_s.setObjectName("text_input_s")
        self.verticalLayout_2.addWidget(self.text_input_s, 0, QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(740, 250, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.serviceStack.addWidget(self.pageSend)
        self.pageSet = QtWidgets.QWidget()
        self.pageSet.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pageSet.setObjectName("pageSet")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageSet)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 75, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem5)
        self.comboBox = QtWidgets.QComboBox(self.pageSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 20))
        self.comboBox.setBaseSize(QtCore.QSize(150, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.variableStack = QtWidgets.QStackedWidget(self.pageSet)
        self.variableStack.setObjectName("variableStack")
        self.pageUpVar = QtWidgets.QWidget()
        self.pageUpVar.setObjectName("pageUpVar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageUpVar)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.pageUpVar)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.tableWidget = QtWidgets.QTableWidget(self.pageUpVar)
        self.tableWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(57)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.variableStack.addWidget(self.pageUpVar)
        self.pageNewVar = QtWidgets.QWidget()
        self.pageNewVar.setObjectName("pageNewVar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageNewVar)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.pageNewVar)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.pageNewVar)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(self.pageNewVar)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.pageNewVar)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_6.addWidget(self.lineEdit_2)
        self.label_6 = QtWidgets.QLabel(self.pageNewVar)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.pageNewVar)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_6.addWidget(self.lineEdit_3)
        self.variableStack.addWidget(self.pageNewVar)
        self.pageBlank = QtWidgets.QWidget()
        self.pageBlank.setObjectName("pageBlank")
        self.variableStack.addWidget(self.pageBlank)
        self.verticalLayout_4.addWidget(self.variableStack)
        spacerItem6 = QtWidgets.QSpacerItem(475, 130, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem6)
        self.serviceStack.addWidget(self.pageSet)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.serviceStack.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.serviceStack.setCurrentIndex(2)
        self.variableStack.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Interface"))
        self.button_refresh.setText(_translate("MainWindow", "Refresh"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Behavior Name"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "beh_1"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Complete"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Send A Signal"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Set Variable"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.button_submit.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "Enter a value for var_1 (string) or press enter or default value(default)"))
        self.label_2.setText(_translate("MainWindow", "Enter a value for var_1 (string) or press enter or default value(default)"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Update Variable"))
        self.comboBox.setItemText(1, _translate("MainWindow", "New Variable"))
        self.label_3.setText(_translate("MainWindow", "Enter a new value for the variable"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "var_1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "String"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Hello"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Enter Variable Name"))
        self.label_5.setText(_translate("MainWindow", "Enter Variable Type"))
        self.label_6.setText(_translate("MainWindow", "Enter Variable Value"))
